name: Techtrend - Package With Dockerhub

on:
  push:
    branches: ['main']
    paths: ['techtrend-project/**']


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v3

      - name: set up Docker Buildx
      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

    
       - name: Build and Push
           id: docker_build
           uses: docker/build-push-action@v2
           with:
              context: .
              push: true
              file: ./techtrend-project/project/Dockerfile
              platforms: linux/amd64, linux/arm64
              tags: amlgalshinawy/techtrends:latest
